#!/usr/bin/env bash
set -e

source /etc/os-release

DEV="0"
LOCAL="0"
ARGV=()
for opt in "$@"
do
	if [ "$opt" == "--dev" ]
	then
        DEV="1"
    elif [ "$opt" == "--local" ]
    then
        LOCAL="1"
	else
		ARGV+=("$opt")
	fi
done

# We may get some chars translated out of Idents.
HYPHENS='@ # $ % ^ & * + = .'
UNDERSCORES='| / < > ,'

POP_DIR="$(dirname "$(dirname "$(readlink -f "$0")")")"
REPOS="http://apt.pop-os.org/staging/"
DEVLINE=''
if [ "$DEV" == "1" ]
then
	DEVLINE='-dev'
    if [ "$LOCAL" == "1" ]
    then
        REPOS="file://${POP_DIR}/_build/repos/dev/"
    else
        REPOS="http://apt.pop-os.org/staging-ubuntu/"
    fi
elif [ "$LOCAL" == "1" ]
then
    REPOS="file://${POP_DIR}/_build/repos/"
fi

LOCALREMOTE=''
if [ "$LOCAL" == "1" ]
then
	LOCALREMOTE='local-'
fi

case "$1" in
	add)
		if [ -z "$2" ]
		then
			echo "$0 $1 [repo]"
			exit 1
		fi

		echo "Adding key"
		sudo apt-key add "${POP_DIR}/scripts/.iso.asc"

		for newrepo in "${ARGV[@]:1}"
		do
			echo "Adding preference for '$newrepo'"
			sudo tee "/etc/apt/preferences.d/pop-os-staging-${newrepo//./_}" > /dev/null <<-EOF
				Package: *
				Pin: release o=pop-os-staging-$newrepo
				Pin-Priority: 1002
			EOF

			echo "Adding repository for '$newrepo'"
			LINE="deb ${REPOS}$newrepo ${UBUNTU_CODENAME} main"
			sudo apt-manage add "${LINE}" \
				--source-code \
				--ident popdev-${LOCALREMOTE}$newrepo${DEVLINE} \
				--name "Pop Development Branch $newrepo" || \
				sudo add-apt-repository -s "${LINE}"
		done
		;;
	remove)
		if [ -z "$2" ]
		then
			echo "$0 $1 [repo]"
			exit 1
		fi

		for newrepo in "${ARGV[@]:1}"
		do
			echo "Removing repository for '$newrepo'"
			r_newrepo=${newrepo//+(@#$%^&*+=.)/-}
			r_newrepo=$newrepo
			for i in $HYPHENS
				do r_newrepo=${r_newrepo//$i/-}
			done
			LINE="deb ${REPOS}$newrepo ${UBUNTU_CODENAME} main"
			sudo echo # Workaround for not having an assume-yes option in remove
			sudo apt-manage remove -y popdev-${LOCALREMOTE}$r_newrepo${DEVLINE} \
				&> /dev/null || \
				sudo add-apt-repository -r -s "${LINE}"

			echo "Removing preference for '$newrepo'"
			sudo rm -f "/etc/apt/preferences.d/pop-os-staging-${newrepo//./_}"
		done
		;;
	local)
		grep "^deb ${REPOS}" /etc/apt/sources.list{,.d/*} | \
			cut -d " " -f2 |
			sed -s "s#${REPOS}##"
		;;
	remote)
		curl -s "${REPOS}" | \
			grep '^<a href="' | \
			cut -d '"' -f 2 | \
			cut -d / -f 1 | \
			sort
		;;
	*)
		echo "$0 add [repo] <--dev> <--local> - add a repository"
		echo "$0 remove [repo] <--dev> <--local> - remove a repository"
		echo "$0 local <--dev> <--local> - show locally added repositories"
		echo "$0 remote <--dev> <--local> - show remote available repositories"
		exit 1
		;;
esac
