#!/usr/bin/env bash
set -e

source /etc/os-release

DEV="0"
LOCAL="0"
ARGV=()
for opt in "$@"
do
	if [ "$opt" == "--dev" ]
	then
        DEV="1"
    elif [ "$opt" == "--local" ]
    then
        LOCAL="1"
	else
		ARGV+=("$opt")
	fi
done

POP_DIR="$(dirname "$(dirname "$(readlink -f "$0")")")"
REPOS="http://apt.pop-os.org/staging/"
if [ "$DEV" == "1" ]
then
    if [ "$LOCAL" == "1" ]
    then
        REPOS="file://${POP_DIR}/_build/repos/dev/"
    else
        REPOS="http://apt.pop-os.org/staging-ubuntu/"
    fi
elif [ "$LOCAL" == "1" ]
then
    REPOS="file://${POP_DIR}/_build/repos/"
fi

case "$1" in
	add)
		if [ -z "$2" ]
		then
			echo "$0 $1 [repo]"
			exit 1
		fi

		echo "Adding key"
		sudo apt-key add "${POP_DIR}/scripts/.iso.asc"

		for newrepo in "${ARGV[@]:1}"
		do
			echo "Adding preference for '$newrepo'"
			sudo tee "/etc/apt/preferences.d/pop-os-staging-${newrepo//./_}" > /dev/null <<-EOF
				Package: *
				Pin: release o=pop-os-staging-$newrepo
				Pin-Priority: 1002
			EOF

			echo "Adding repository for '$newrepo'"
			sudo apt-manage add "deb ${REPOS}$newrepo ${UBUNTU_CODENAME} main" \
				--source-code \
				--ident popdev-$newrepo \
				--name "Pop Development Branch $newrepo" || \
				sudo add-apt-repository -s "deb ${REPOS}$newrepo ${UBUNTU_CODENAME} main"
		done
		;;
	remove)
		if [ -z "$2" ]
		then
			echo "$0 $1 [repo]"
			exit 1
		fi

		for newrepo in "${ARGV[@]:1}"
		do
			echo "Removing repository for '$newrepo'"
			sudo apt-manage remove popdev-$newrepo || \
				sudo add-apt-repository -r -s \
					"deb ${REPOS}$newrepo ${UBUNTU_CODENAME} main"

			echo "Removing preference for '$newrepo'"
			sudo rm -f "/etc/apt/preferences.d/pop-os-staging-${newrepo//./_}"
		done
		;;
	local)
		grep "^deb ${REPOS}" /etc/apt/sources.list | \
			cut -d " " -f2 |
			sed -s "s#${REPOS}##"
		;;
	remote)
		curl -s "${REPOS}" | \
			grep '^<a href="' | \
			cut -d '"' -f 2 | \
			cut -d / -f 1 | \
			sort
		;;
	*)
		echo "$0 add [repo] <--dev> <--local> - add a repository"
		echo "$0 remove [repo] <--dev> <--local> - remove a repository"
		echo "$0 local <--dev> <--local> - show locally added repositories"
		echo "$0 remote <--dev> <--local> - show remote available repositories"
		exit 1
		;;
esac
