#!/usr/bin/env bash

set -e

source /etc/os-release

POP_DIR="$(dirname "$(dirname "$(readlink -f "$0")")")"
REPOS="ftp://209.212.58.90/repos/"

case "$1" in
	add)
		if [ -z "$2" ]
		then
			echo "$0 $1 [repo]"
			exit 1
		fi

		echo "Adding key"
		sudo apt-key add "${POP_DIR}/scripts/.iso.asc"

		echo "Adding preference"
		sudo tee "/etc/apt/preferences.d/pop-os-staging-$2" > /dev/null <<-EOF
			Package: *
			Pin: release o=pop-os-staging-$2
			Pin-Priority: 1001
		EOF

		echo "Adding repository"
		sudo add-apt-repository -s "deb [arch=amd64] ${REPOS}$2 ${UBUNTU_CODENAME} main"
		;;
	remove)
		if [ -z "$2" ]
		then
			echo "$0 $1 [repo]"
			exit 1
		fi

		echo "Removing repository"
		sudo add-apt-repository -r -s "deb [arch=amd64] ${REPOS}$2 ${UBUNTU_CODENAME} main"

		echo "Removing preference"
		sudo rm -f "/etc/apt/preferences.d/pop-os-staging-$2"
		;;
	local)
		grep "^deb \\[arch=amd64\\] ${REPOS}" /etc/apt/sources.list | \
			cut -d " " -f3 |
			cut -d "/" -f5
		;;
	remote)
		curl -l --user anonymous:anonymous "${REPOS}"
		;;
	*)
		echo "$0 add [repo] - add a repository"
		echo "$0 remove [repo] - remove a repository"
		echo "$0 local - show locally added repositories"
		echo "$0 remote - show remote available repositories"
		exit 1
		;;
esac
