#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys

from lib import foreach_repo, github

parser = argparse.ArgumentParser(description="Show branches of Pop!_OS repositories")
parser.add_argument("repos", nargs="*", default=[])
args = parser.parse_args(sys.argv[1:])

def callback(repo):
    print("\x1B[1m" + repo["name"] + "\x1B[0m")

    for branch in github(repo["branches_url"].replace("{/branch}", "")):
        if branch["name"] == repo["default_branch"]:
            print(" * " + branch["name"])
        else:
            print("   " + branch["name"])

foreach_repo(callback, args.repos)
