#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys
import json
from lib import foreach_repo, github

out = {}
parser = argparse.ArgumentParser(description="Show branches of Pop!_OS repositories")
parser.add_argument("repos", nargs="*", default=[])
parser.add_argument("--json",action='store_true',help="Set output format to json")
args = parser.parse_args()

def callback(repo):
	if not args.json:
		print("\x1B[1m" + repo["name"] + "\x1B[0m")
	else:
		out[repo["name"]] = []
	for branch in github(repo["branches_url"].replace("{/branch}", "")):
		if args.json:
			out[repo["name"]].append(branch["name"])
		else:
			if branch["name"] == repo["default_branch"]:
				print(" * " + branch["name"])
			else:
				print("   " + branch["name"])

foreach_repo(callback, args.repos)
if args.json:
	print(json.dumps(out))
