#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys
import json
from lib import foreach_repo, github

out = {}
parser = argparse.ArgumentParser(description="Show branches of Pop!_OS repositories")
parser.add_argument("repos", nargs="*", default=[])
parser.add_argument("--output",help="Set output format (Currently only json)")
args = parser.parse_args()

def callback(repo):
	if args.output == None:
		print("\x1B[1m" + repo["name"] + "\x1B[0m")
	else:
		out[repo["name"]] = []
	for branch in github(repo["branches_url"].replace("{/branch}", "")):
		if branch["name"] == repo["default_branch"]:
			if args.output == None:
				print(" * " + branch["name"])
			else:
				out[repo["name"]].append(branch["name"])
		else:
			if args.output == None:
				print("   " + branch["name"])
			else:
				out[repo["name"]].append(branch["name"])

foreach_repo(callback, args.repos)
if args.output != None:
	print(json.dumps(out))
