#!/usr/bin/env python3

import argparse
from collections import namedtuple
import sys
import os
from os import path
import shutil
from subprocess import check_call, check_output
import tempfile

from lib import foreach_repo

Series = namedtuple('Series', 'codename version')

parser = argparse.ArgumentParser(description="Source package all Pop!_OS repositories")
parser.add_argument("repos", nargs="*", default=[])
args = parser.parse_args(sys.argv[1:])

POP_DIR = path.dirname(path.dirname(path.abspath(__file__)))
BUILD_DIR = path.join(POP_DIR, '_build')
GIT_DIR = path.join(BUILD_DIR, 'git')
SOURCE_DIR = path.join(BUILD_DIR, 'source')
BINARY_DIR = path.join(BUILD_DIR, 'binary')

build_series = {
    'artful': '17.10',
    'bionic': '18.04',
}

CHANGELOG = """{name} ({version}) {codename}; urgency=medium

  * Auto Build

 -- {maintainer}  {datetime}
"""


def iprint(level, value):
    indent = ' ' * (level * 4)
    print('>>> ' + indent + str(value))


def git_ids_and_branches(cwd):
    """
    Returns a `dict` mapping each commit ID to a list of branches.

    `git ls-remote` will return something like::

        f73e8fc2c5bb5756032c35b6be1fcd84106413b1	refs/heads/overhaul
        ffb788cccfe0cd7feedcfe8f0b8e9154097a46ca	refs/heads/master
        f73e8fc2c5bb5756032c35b6be1fcd84106413b1	refs/heads/test_bionic

    For which this function would return::

        {
            'f73e8fc2c5bb5756032c35b6be1fcd84106413b1': ['overhaul', 'test_bionic'],
            'ffb788cccfe0cd7feedcfe8f0b8e9154097a46ca':	['master'],
        }
    """
    check_call(['git', 'fetch', 'origin'], cwd=cwd)
    o = check_output(['git', 'ls-remote', '--heads', 'origin'], cwd=cwd)
    prefix = 'refs/heads/'
    result = {}
    for line in o.decode().splitlines():
        (_id, rawbranch) = line.split('\t')
        assert rawbranch.startswith(prefix)
        branch = rawbranch[len(prefix):]
        if _id not in result:
            result[_id] = []
        result[_id].append(branch)
    return result


def git_clean(cwd):
    check_call(['git', 'clean', '-xfd'], cwd=cwd)


def git_checkout_id(cwd, _id):
    check_call(['git', 'checkout', '--force', '--detach', _id], cwd=cwd)
    check_call(['git', 'submodule', 'sync', '--recursive'], cwd=cwd)
    check_call(['git', 'submodule', 'update', '--init', '--recursive'], cwd=cwd)
    git_clean(cwd)


def git_timestamp_id(cwd, _id):
    o = check_output(["git", "log", "-1", "--pretty=format:%ct", _id], cwd=cwd)
    return o.decode().strip()


def git_datetime_id(cwd, _id):
    o = check_output(["git", "log", "-1", "--pretty=format:%cD", _id], cwd=cwd)
    return o.decode().strip()


def git_archive_id(cwd, _id, archive):
    return check_output(["git", "archive", "--format", "tar", "-o", archive, _id], cwd=cwd)


def parse_branch(branch):
    parts = branch.split('_')
    assert len(parts) <= 2
    pocket = parts[0]
    codename = (None if len(parts) < 2 else parts[1])
    return (pocket, codename)


def iter_series(branches):
    for b in branches:
        (pocket, codename) = parse_branch(b)
        if codename is None:
            for (codename, version) in build_series.items():
                yield (Series(codename, version), pocket)
        else:
            yield (Series(codename, build_series[codename]), pocket)


def expand_series(branches):
    result = {}
    for (series, pocket) in iter_series(branches):
        if series not in result:
            result[series] = set()
        result[series].add(pocket)
    return result


def read_source_package_name(cwd):
    control = path.join(cwd, 'debian', 'control')
    with open(control, 'r') as fp:
        (key, value) = fp.readline().rstrip().split(': ')
        assert key == 'Source'
        return value


GitTar = namedtuple('GitTar', 'id timestamp datetime archive')

def git_tar(cwd, _id):
    timestamp = git_timestamp_id(cwd, _id)
    datetime = git_datetime_id(cwd, _id)
    archive = path.join(GIT_DIR, _id)
    git_archive_id(cwd, _id, archive)
    return GitTar(_id, timestamp, datetime, archive)


def dpkg_source(name, git, series):
    prefix = name + "_" + git.id + "_" + series.codename + "_"
    with tempfile.TemporaryDirectory(prefix=prefix) as tempdir:
        print(tempdir)

        check_call(['tar', 'xf', git.archive], cwd=tempdir)

        if not path.isdir(path.join(tempdir, 'debian')):
             print('no debian dir: {!r}'.format(tempdir))
             return

        source_name = read_source_package_name(tempdir)
        version = '~'.join(['0', git.timestamp, series.version, git.id])

        changelog = CHANGELOG.format(
            name=source_name,
            version=version,
            codename=series.codename,
            maintainer='Pop Launchpad <pop.launchpad@system76.com>',
            datetime=git.datetime,
        )

        print(changelog)

        with open(path.join(tempdir, 'debian', 'changelog'), 'w') as fp:
            fp.write(changelog)

        env = {"SOURCE_DATE_EPOCH": str(git.timestamp)}
        check_call(['dpkg-source', '--build', tempdir], cwd=SOURCE_DIR, env=env)


def build_stuff_we_need(name):
    cwd = path.join(POP_DIR, name)

    print('')
    iprint(0, name + ": " + cwd)

    if not path.exists(cwd):
        print('did not find: {!r}'.format(cwd))
        return

    ids = git_ids_and_branches(cwd)
    for (_id, branches) in sorted(ids.items()):
        git = git_tar(cwd, _id)

        iprint(1, git.id + ": " + git.datetime)

        expanded = expand_series(branches)
        for (series, pocket) in sorted(expanded.items()):
            iprint(2, series)

            dpkg_source(name, git, series)

            for pocket in sorted(pocket):
                iprint(3, pocket)


def build_sources_callback(repo):
    name =  repo['name']

    if name in (
        'code-of-conduct',
        'docs',
        'gnome-control-center',
        'gnome-initial-setup',
        'iso',
        'icon-theme',
        'shop',
        'wallpapers'
    ):
        print('skipping {!r}'.format(name))
        return

    build_stuff_we_need(name)


def recreate_dir(d):
    if path.isdir(d):
        shutil.rmtree(d)
    os.mkdir(d)


def build_sources():
    recreate_dir(BUILD_DIR)
    os.mkdir(GIT_DIR)
    os.mkdir(SOURCE_DIR)
    foreach_repo(build_sources_callback, args.repos)


build_sources()
