#!/usr/bin/env python3

# Setting up sbuild requires the following commands:
#     sudo apt install sbuild
#     sudo sbuild-adduser "$USER"
#     newgrp sbuild
#     sudo sbuild-createchroot --include=eatmydata,ccache,gnupg --components=main,restricted,universe,multiverse artful /srv/chroot/artful-amd64-sbuild http://archive.ubuntu.com/ubuntu
#
# Put the following in ~/.sbuildrc:
#     $build_arch_all = 1;
#     $distribution = 'artful';

import argparse
import os
import os.path
import subprocess
import sys

parser = argparse.ArgumentParser(description="Build source packages")
args = parser.parse_args(sys.argv[1:])

if os.path.exists("_build/deb_source"):
    for root, dirs, files in os.walk("_build/deb_source"):
        for entry in files:
            parts = os.path.splitext(entry)
            if parts[1] == ".dsc":
                print("\x1B[1m" + parts[0] + "\x1B[0m")

                changes = parts[0] + "_amd64.changes"
                if os.path.exists(os.path.join(root, changes)):
                    print(entry + " already built by " + changes)
                else:
                    print("building with sbuild")
                    subprocess.run([
                        "sbuild",
                        "--extra-repository=deb http://ppa.launchpad.net/system76/pop/ubuntu artful main",
                        "--extra-repository-key=" + os.path.abspath("scripts/.ppa.asc"),
                        entry
                    ], check=True, cwd=root)
