#!/usr/bin/env python3

import argparse
import os.path
import shutil
import subprocess
import sys

from lib import foreach_repo

parser = argparse.ArgumentParser(description="Clone all Pop!_OS repositories")
parser.add_argument("--clean", action="store_true")
parser.add_argument("--ssh", action="store_true")
parser.add_argument("repos", nargs="*", default=[])
args = parser.parse_args(sys.argv[1:])

def callback(repo):
    print("\x1B[1m" + repo["name"] + "\x1B[0m", flush=True)

    if repo["name"] == "pop":
        print("skipping", flush=True)
        return

    if args.ssh:
        url = repo["ssh_url"]
    else:
        url = repo["clone_url"]

    if os.path.exists(repo["name"]):
        print("already exists", flush=True)
    else:
        subprocess.run(["git", "clone", "--recursive", url, repo["name"]], check=True)

repos = foreach_repo(callback, args.repos)

if args.clean:
    for entry in os.listdir("."):
        # Skip valid repos
        if entry in repos:
            continue
        # Delete repos that are no longer valid
        if os.path.isdir(os.path.join(entry, ".git")):
            print("\x1B[1mremoving " + entry + "\x1B[0m", flush=True)
            shutil.rmtree(entry)
