#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys

from lib import foreach_repo

parser = argparse.ArgumentParser(description="Clone all Pop!_OS repositories")
parser.add_argument("--ssh", action="store_true")
parser.add_argument("repos", nargs="*", default=[])
args = parser.parse_args(sys.argv[1:])

def clone(repo):
    print("\x1B[1m" + repo["name"] + "\x1B[0m")

    if args.ssh:
        url = repo["ssh_url"]
    else:
        url = repo["clone_url"]

    if os.path.exists(repo["name"]):
        print("already exists")
    else:
        subprocess.run(["git", "clone", "--recursive", url, repo["name"]], check=True)

foreach_repo(clone, args.repos)
