#!/usr/bin/env python3

import argparse
import os
import os.path
import subprocess
import sys

from lib import foreach_repo

parser = argparse.ArgumentParser(description="Build all Pop!_OS repositories")
parser.add_argument("repos", nargs="*", default=[])
args = parser.parse_args(sys.argv[1:])

def callback(repo):
    print("\x1B[1m" + repo["name"] + "\x1B[0m")

    if os.path.exists(repo["name"]):
        if os.path.exists(os.path.join(repo["name"], "debian")):
            dpkg = os.path.join("dpkg", repo["name"])
            if not os.path.exists(dpkg):
                os.makedirs(dpkg)

            subprocess.run(["sbuild", os.path.abspath(repo["name"])], check=True, cwd=dpkg)
        else:
            print("debian directory not found")
    else:
        print("does not exist")

foreach_repo(callback, args.repos)
