#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys

from lib import foreach_repo

parser = argparse.ArgumentParser(description="Version all Pop!_OS repositories")
args = parser.parse_args(sys.argv[1:])

def version(repo):
    print("Versioning " + repo["name"])
    if os.path.exists(repo["name"]):
        if os.path.exists(os.path.join(repo["name"], "debian", "changelog")):
            source = subprocess.run(["dpkg-parsechangelog", "--show-field", "Source"], check=True, cwd=repo["name"], stdout=subprocess.PIPE)
            version = subprocess.run(["dpkg-parsechangelog", "--show-field", "Version"], check=True, cwd=repo["name"], stdout=subprocess.PIPE)
            print(source.stdout.decode("utf-8").strip() + " " + version.stdout.decode("utf-8").strip())
        else:
            print("debian/changelog not found")
    else:
        print(repo["name"] + " does not exist")

foreach_repo(version)
