#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys

from lib import foreach_repo

parser = argparse.ArgumentParser(description="Version all Pop!_OS repositories")
parser.add_argument("repos", nargs="*", default=[])
args = parser.parse_args(sys.argv[1:])

def callback(repo):
    print("\x1B[1m" + repo["name"] + "\x1B[0m")

    if os.path.exists(repo["name"]):
        if os.path.exists(os.path.join(repo["name"], "debian", "changelog")):
            source = subprocess.run(["dpkg-parsechangelog", "--show-field", "Source"], check=True, cwd=repo["name"], stdout=subprocess.PIPE)
            version = subprocess.run(["dpkg-parsechangelog", "--show-field", "Version"], check=True, cwd=repo["name"], stdout=subprocess.PIPE)
            print(source.stdout.decode().strip() + "_" + version.stdout.decode().strip())
        else:
            print("debian/changelog not found")
    else:
        print("does not exist")

foreach_repo(callback, args.repos)
