#!/usr/bin/env python3

import argparse
import sys

from lib import foreach_repo

parser = argparse.ArgumentParser(description="Generate gitignore file")
args = parser.parse_args(sys.argv[1:])

f = open(".gitignore", "w")

def ignore(repo):
    print("Ignoring " + repo["name"])
    f.write("/" + repo["name"] + "/\n")

foreach_repo(ignore)

f.close()
