#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys

from lib import foreach_repo

parser = argparse.ArgumentParser(description="Pull all Pop!_OS repositories")
parser.add_argument("repos", nargs="*", default=[])
args = parser.parse_args(sys.argv[1:])

def pull(repo):
    print("\x1B[1m" + repo["name"] + "\x1B[0m")

    if os.path.exists(repo["name"]):
        subprocess.run(["git", "-C", repo["name"], "pull"], check=True)
        subprocess.run(["git", "-C", repo["name"], "submodule", "update", "--init", "--recursive"], check=True)
    else:
        print("does not exist")

foreach_repo(pull, args.repos)
