#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys

from lib import foreach_repo

parser = argparse.ArgumentParser(description="Pull all Pop!_OS repositories")

def pull(repo):
    print("Pulling " + repo["name"])
    if os.path.exists(repo["name"]):
        subprocess.run(["git", "-C", repo["name"], "pull"], check=True)
        subprocess.run(["git", "-C", repo["name"], "submodule", "update", "--init", "--recursive"], check=True)
    else:
        print(repo["name"] + " does not exist")

foreach_repo(pull)
