#!/usr/bin/env bash

function git_remote {
    echo -e "\x1B[1m$1: $2 = $3\x1B[0m"
    if git -C "$1" remote | grep "^$2\$" > /dev/null
    then
        git -C "$1" remote set-url "$2" "$3"
    else
        git -C "$1" remote add "$2" "$3"
    fi
    git -C "$1" remote update "$2"
    git -C "$1" remote prune "$2"
}

function debian_gnome {
    git_remote "$1" debian "https://salsa.debian.org/gnome-team/$1.git"
}

git_remote cosmic-dock upstream "https://github.com/micheleg/dash-to-dock.git"
git_remote desktop-icons-ng upstream "https://gitlab.com/rastersoft/desktop-icons-ng.git"
git_remote dwarves debian "https://salsa.debian.org/debian/dwarves.git"
git_remote fwupd debian "https://salsa.debian.org/efi-team/fwupd.git"
git_remote fwupd upstream "https://github.com/fwupd/fwupd.git"
git_remote gdm3 debian "https://salsa.debian.org/gnome-team/gdm.git"
debian_gnome gnome-control-center
debian_gnome gnome-initial-setup
debian_gnome gnome-online-accounts
debian_gnome gnome-settings-daemon
debian_gnome gnome-shell
git_remote gnome-shell-extension-vertical-overview upstream "https://github.com/RensAlthuis/vertical-overview.git"
debian_gnome gnome-terminal
git_remote libdrm debian "https://salsa.debian.org/xorg-team/lib/libdrm.git"
git_remote libhandy debian "https://salsa.debian.org/DebianOnMobile-team/libhandy-1.git"
git_remote mesa debian https://salsa.debian.org/xorg-team/lib/mesa.git
git_remote mesa upstream https://gitlab.freedesktop.org/mesa/mesa.git
git_remote mozc debian https://salsa.debian.org/debian/mozc.git
debian_gnome mutter
git_remote ninja-build debian "https://salsa.debian.org/debian/ninja-build.git"
git_remote steam debian "https://salsa.debian.org/games-team/steam.git"
git_remote systemd ubuntu "https://git.launchpad.net/~ubuntu-core-dev/ubuntu/+source/systemd"
git_remote touchegg upstream "https://github.com/JoseExposito/touchegg.git"
git_remote virtualbox debian "https://salsa.debian.org/pkg-virtualbox-team/virtualbox.git"
