#!/usr/bin/env python3

import argparse
import os
import os.path
import subprocess
import sys

parser = argparse.ArgumentParser(description="Build source packages")
args = parser.parse_args(sys.argv[1:])

if os.path.exists("dpkg"):
    for root, dirs, files in os.walk("dpkg"):
        for entry in files:
            parts = os.path.splitext(entry)
            if parts[1] == ".dsc":
                print("\x1B[1m" + parts[0] + "\x1B[0m")

                deb_arch = parts[0] + "_amd64.deb"
                deb_all = parts[0] + "_all.deb"
                if os.path.exists(os.path.join(root, deb_all)):
                    print(deb_all + " already built")
                elif os.path.exists(os.path.join(root, deb_arch)):
                    print(deb_arch + " already built")
                else:
                    print("building with sbuild")
                    subprocess.run(["sbuild", entry], check=True, cwd=root)
