#!/usr/bin/env python3

import argparse
import distro
import os
from os import path
from subprocess import check_call
import sys

parser = argparse.ArgumentParser(description="Run Pop!_OS build process")
parser.add_argument("--dev", action="store_true")
parser.add_argument("--dist", default=distro.codename())
parser.add_argument("--arch", default="amd64")
parser.add_argument("--update", action="store_true")
parser.add_argument("repo")
args = parser.parse_args(sys.argv[1:])

def ppa_url(ppa):
    return "http://ppa.launchpad.net/" + ppa + "/ubuntu"

if args.dev:
    os.environ["S76_DEV"] = "1"
    apt_key = ".ppa-dev.asc"
    apt_release = ppa_url("system76-dev/stable")
    apt_proposed = ppa_url("system76-dev/pre-stable")
elif args.dist in ["bionic", "focal"]:
    apt_key = ".ppa.asc"
    apt_release = ppa_url("system76/pop")
    apt_proposed = ppa_url("system76/proposed")
else:
    apt_key = ".iso.asc"
    apt_release = "http://apt.pop-os.org/release"
    apt_proposed = "http://apt.pop-os.org/staging/master"


chroot_path = "/srv/chroot/" + args.dist + "-" + args.arch + "-sbuild"
if not path.exists(chroot_path):
    check_call([
        "sudo", "sbuild-createchroot",
        "--include=gnupg",
        "--components=main,restricted,universe,multiverse",
        "--arch=" + args.arch,
        args.dist,
        chroot_path,
        "http://archive.ubuntu.com/ubuntu"
    ])

if args.update:
    check_call([
        "sudo", "sbuild-update",
        "--update",
        "--dist-upgrade",
        "--clean",
        "--autoclean",
        "--autoremove",
        "--arch=" + args.arch,
        args.dist
    ])

sbuild = [
    "sbuild",
    "--dist=" + args.dist,
    "--arch=" + args.arch,
    "--extra-repository=deb http://us.archive.ubuntu.com/ubuntu/ " + args.dist + "-updates main restricted universe multiverse",
    "--extra-repository=deb-src http://us.archive.ubuntu.com/ubuntu/ " + args.dist + "-updates main restricted universe multiverse",
    "--extra-repository=deb http://us.archive.ubuntu.com/ubuntu/ " + args.dist + "-security main restricted universe multiverse",
    "--extra-repository=deb-src http://us.archive.ubuntu.com/ubuntu/ " + args.dist + "-security main restricted universe multiverse",
    "--extra-repository=deb " + apt_release + " " + args.dist + " main",
    "--extra-repository=deb-src " + apt_release + " " + args.dist + " main",
    "--extra-repository=deb " + apt_proposed + " " + args.dist + " main",
    "--extra-repository=deb-src " + apt_proposed + " " + args.dist + " main",
    "--extra-repository-key=" + path.join(os.getcwd(), "scripts", apt_key),
    "--no-apt-distupgrade",
]

check_call(sbuild, cwd=args.repo)
