#!/usr/bin/env bash

set -e

codenames=(
    bionic
    cosmic
    disco
    #eoan
)

for codename in "${codenames[@]}"
do
    CHROOT="/srv/chroot/${codename}-amd64-sbuild"
    test -e "${CHROOT}" >/dev/null || sudo sbuild-createchroot \
        --include=eatmydata,ccache,gnupg \
        --components=main,restricted,universe,multiverse \
        "${codename}" \
        "${CHROOT}" \
        "http://archive.ubuntu.com/ubuntu"

    sudo sbuild-update \
        --update \
        --dist-upgrade \
        --clean \
        --autoclean \
        --autoremove \
        "$codename"
done
