#!/usr/bin/env bash

set -e

codenames=(
    bionic
    disco
    eoan
)

archs=(
    amd64
    i386
)

for codename in "${codenames[@]}"
do
  for arch in "${archs[@]}"
  do
    CHROOT="/srv/chroot/${codename}-${arch}-sbuild"
    test -e "${CHROOT}" >/dev/null || sudo sbuild-createchroot \
        --include=eatmydata,ccache,gnupg \
        --components=main,restricted,universe,multiverse \
        --arch="${arch}" \
        "${codename}" \
        "${CHROOT}" \
        "http://archive.ubuntu.com/ubuntu"

    sudo sbuild-update \
        --update \
        --dist-upgrade \
        --clean \
        --autoclean \
        --autoremove \
        --arch="${arch}" \
        "$codename"
  done
done
