#!/usr/bin/env python3

import argparse
import os.path
import sys

from lib import foreach_repo, github

parser = argparse.ArgumentParser(description="Check subscription status on all Pop!_OS repositories")
parser.add_argument("repos", nargs="*", default=[])
args = parser.parse_args(sys.argv[1:])

def callback(repo):
    print("\x1B[1m" + repo["name"] + "\x1B[0m")
    
    try:
        for subscriber in github(repo["subscribers_url"]):
            print(subscriber["login"])
    except Exception as ex:
        print(ex)
    

foreach_repo(callback, args.repos)
