#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys
from lib import foreach_repo, github, DEV_REPOS

out = {}
parser = argparse.ArgumentParser(description="Show branches of Pop!_OS repositories")
parser.add_argument("repos", nargs="*", default=[])
args = parser.parse_args()

def callback(repo):
	if os.path.exists(os.path.join(repo["name"], "debian")):
		has_master_wildcard = False
		has_master_focal = False
		has_master_jammy = False
		has_master_noble = False
		for branch in github(repo["branches_url"].replace("{/branch}", "")):
			if branch["name"] == "master":
				has_master_wildcard = True
			if branch["name"] == "master_focal":
				has_master_focal = True
			if branch["name"] == "master_jammy":
				has_master_jammy = True

		if repo["name"] in DEV_REPOS:
			suffix = "dev"
		else:
			suffix = "pop"

		if has_master_wildcard or has_master_focal:
			print("focal," + suffix + " " + repo["name"])
		if has_master_wildcard or has_master_jammy:
			print("jammy," + suffix + " " + repo["name"])
		if has_master_wildcard or has_master_noble:
			print("noble," + suffix + " " + repo["name"])

foreach_repo(callback, args.repos)
