#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys
from lib import foreach_repo, github, DEV_REPOS

out = {}
parser = argparse.ArgumentParser(description="Show branches of Pop!_OS repositories")
parser.add_argument("repos", nargs="*", default=[])
args = parser.parse_args()

def callback(repo):
	if os.path.exists(os.path.join(repo["name"], "debian")):
		branches = []
		for branch in github(repo["branches_url"].replace("{/branch}", "")):
			branches.append(branch["name"])

		if repo["name"] in DEV_REPOS:
			suffix = "dev"
		else:
			suffix = "pop"

		for codename in ["focal", "jammy", "noble", "resolute"]:
			matches = []
			wildcard_master = "master"
			codename_master = wildcard_master + "_" + codename
			if codename_master in branches:
				matches.append(codename_master)
			if wildcard_master in branches:
				matches.append(wildcard_master)
			if len(matches) > 0:
				print(codename + "," + suffix + " " + ",".join(matches) + " " + repo["name"])

foreach_repo(callback, args.repos)
