/// Repos to build for both Pop and Ubuntu
pub static DEV_REPOS: &'static [&'static str] = &[
    "accountsservice",
    "alsa-ucm-conf",
    "alsa-utils",
    "amd-ppt-bin",
    "amd64-microcode",
    "bcmwl",
    "bluez",
    "directx-headers",
    "distinst",
    "dwarves",
    "egl-wayland",
    "firmware-manager",
    "fwupd",
    "fwupd-efi",
    "gdm3",
    "gnome-desktop3",
    "gnome-settings-daemon",
    "gnome-shell",
    "gnome-shell-extension-system76-power",
    "hidpi-daemon",
    "kbuild",
    "libabigail",
    "libasound2",
    "libbpf",
    "libdrm",
    "libtraceevent",
    "libtracefs",
    "libvdpau",
    "libxmlb",
    "linux",
    "linux-firmware",
    "mesa",
    "meson-1.5",
    "ninja-build",
    "nvidia-graphics-drivers",
    "nvidia-graphics-drivers-470",
    "nvidia-graphics-drivers-565",
    "nvidia-graphics-drivers-595",
    "spirv-headers",
    "spirv-llvm-translator-15",
    "spirv-tools",
    "switcheroo-control",
    "system76-acpi-dkms",
    "system76-dkms",
    "system76-driver",
    "system76-firmware",
    "system76-io-dkms",
    "system76-keyboard-configurator",
    "system76-oled",
    "system76-power",
    "system76-ubuntu-repo",
    "system76-wallpapers",
    "systemd",
    "ubuntu-drivers-common",
    "virtualbox",
    "virtualbox-ext-pack",
    "wayland",
    "wayland-protocols",
    "zfs-linux",
];

/// Repos from DEV_REPOS to build for only Ubuntu
pub static DEV_ONLY_REPOS: &'static [&'static str] = &["system76-ubuntu-repo"];

/// Repos that no longer support Pop 22.04, and must not be build wildcard branches (master) for jammy
pub static JAMMY_EXCLUDED_REPOS: &'static [&'static str] = &[
    "cosmic-bg",
    "cosmic-comp",
    "cosmic-settings",
    "xdg-desktop-portal-cosmic",
];
